"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isNumber = exports.isBoolean = exports.isString = exports.isObject = exports.isArray = exports.isFunction = void 0;
const isFunction = (value) => typeof value === 'function';
exports.isFunction = isFunction;
const isArray = (value) => Array.isArray(value);
exports.isArray = isArray;
const toString = Object.prototype.toString;
const isObject = (value) => toString.call(value) === '[object Object]';
exports.isObject = isObject;
const isString = (value) => typeof value === 'string';
exports.isString = isString;
const isBoolean = (value) => typeof value === 'boolean';
exports.isBoolean = isBoolean;
const isNumber = (value) => typeof value === 'number';
exports.isNumber = isNumber;
